// Bibliothèque curatée : titres connus, BPMs vérifiés, durées en secondes.
// genres: motown | hiphop | electro | rock | lofi | myriam (Easter egg 175+ BPM)

const MUSIC_LIBRARY = [

  // ─── MOTOWN / SOUL ──────────────────────────────────────────────────────── ~94 min
  { title: "Dancing in the Street",          artist: "Martha Reeves & The Vandellas",   bpm: 126, duration: 161, genres: ["motown"] },
  { title: "Heat Wave",                      artist: "Martha Reeves & The Vandellas",   bpm: 167, duration: 164, genres: ["motown"] },
  { title: "Nowhere to Run",                 artist: "Martha Reeves & The Vandellas",   bpm: 130, duration: 174, genres: ["motown"] },
  { title: "I Can't Help Myself",            artist: "Four Tops",                       bpm: 127, duration: 165, genres: ["motown"] },
  { title: "Reach Out I'll Be There",        artist: "Four Tops",                       bpm: 120, duration: 174, genres: ["motown"] },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye",                  bpm: 117, duration: 194, genres: ["motown"] },
  { title: "Ain't No Mountain High Enough",  artist: "Marvin Gaye & Tammi Terrell",    bpm: 129, duration: 147, genres: ["motown"] },
  { title: "What's Going On",                artist: "Marvin Gaye",                    bpm: 101, duration: 234, genres: ["motown"] },
  { title: "Superstition",                   artist: "Stevie Wonder",                  bpm: 101, duration: 245, genres: ["motown"] },
  { title: "Signed, Sealed, Delivered",      artist: "Stevie Wonder",                  bpm: 109, duration: 161, genres: ["motown"] },
  { title: "Uptight (Everything's Alright)", artist: "Stevie Wonder",                  bpm: 134, duration: 174, genres: ["motown"] },
  { title: "Sir Duke",                       artist: "Stevie Wonder",                  bpm: 107, duration: 232, genres: ["motown"] },
  { title: "Master Blaster (Jammin')",       artist: "Stevie Wonder",                  bpm: 131, duration: 308, genres: ["motown"] },
  { title: "Higher Ground",                  artist: "Stevie Wonder",                  bpm: 126, duration: 226, genres: ["motown"] },
  { title: "Ain't Too Proud to Beg",         artist: "The Temptations",                bpm: 120, duration: 153, genres: ["motown"] },
  { title: "My Girl",                        artist: "The Temptations",                bpm: 105, duration: 165, genres: ["motown"] },
  { title: "Get Ready",                      artist: "The Temptations",                bpm: 135, duration: 159, genres: ["motown"] },
  { title: "Ball of Confusion",              artist: "The Temptations",                bpm:  80, duration: 249, genres: ["motown"] },
  { title: "Papa Was a Rollin' Stone",       artist: "The Temptations",                bpm:  90, duration: 414, genres: ["motown"] },
  { title: "I Want You Back",                artist: "Jackson 5",                      bpm:  98, duration: 179, genres: ["motown"] },
  { title: "ABC",                            artist: "Jackson 5",                      bpm:  94, duration: 177, genres: ["motown"] },
  { title: "Stop! In the Name of Love",      artist: "The Supremes",                   bpm: 115, duration: 173, genres: ["motown"] },
  { title: "Baby Love",                      artist: "The Supremes",                   bpm: 136, duration: 158, genres: ["motown"] },
  { title: "You Keep Me Hangin' On",         artist: "The Supremes",                   bpm: 128, duration: 163, genres: ["motown"] },
  { title: "Going to a Go-Go",               artist: "The Miracles",                   bpm: 129, duration: 158, genres: ["motown"] },
  { title: "Shop Around",                    artist: "The Miracles",                   bpm: 120, duration: 167, genres: ["motown"] },
  { title: "Tears of a Clown",               artist: "Smokey Robinson & The Miracles", bpm: 128, duration: 179, genres: ["motown"] },
  { title: "Do You Love Me",                 artist: "The Contours",                   bpm: 151, duration: 173, genres: ["motown"] },
  { title: "Shotgun",                        artist: "Jr. Walker & The All Stars",     bpm: 120, duration: 185, genres: ["motown"] },

  // ─── HIP-HOP ─────────────────────────────────────────────────────────────── ~97 min
  { title: "Lose Yourself",                  artist: "Eminem",                         bpm: 171, duration: 326, genres: ["hiphop"] },
  { title: "Stronger",                       artist: "Kanye West",                     bpm: 104, duration: 312, genres: ["hiphop"] },
  { title: "POWER",                          artist: "Kanye West",                     bpm: 154, duration: 292, genres: ["hiphop"] },
  { title: "All Falls Down",                 artist: "Kanye West",                     bpm:  82, duration: 237, genres: ["hiphop"] },
  { title: "New Slaves",                     artist: "Kanye West",                     bpm:  90, duration: 267, genres: ["hiphop"] },
  { title: "All of the Lights",              artist: "Kanye West",                     bpm: 119, duration: 297, genres: ["hiphop"] },
  { title: "Monster",                        artist: "Kanye West ft. Jay-Z & Nicki Minaj", bpm: 131, duration: 358, genres: ["hiphop"] },
  { title: "Black Skinhead",                 artist: "Kanye West",                     bpm: 150, duration: 220, genres: ["hiphop"] },
  { title: "HUMBLE.",                        artist: "Kendrick Lamar",                 bpm: 150, duration: 177, genres: ["hiphop"] },
  { title: "DNA.",                           artist: "Kendrick Lamar",                 bpm: 152, duration: 186, genres: ["hiphop"] },
  { title: "m.A.A.d city",                   artist: "Kendrick Lamar",                 bpm: 109, duration: 353, genres: ["hiphop"] },
  { title: "Swimming Pools",                 artist: "Kendrick Lamar",                 bpm:  84, duration: 314, genres: ["hiphop"] },
  { title: "Mask Off",                       artist: "Future",                         bpm: 150, duration: 204, genres: ["hiphop"] },
  { title: "SICKO MODE",                     artist: "Travis Scott",                   bpm: 155, duration: 313, genres: ["hiphop"] },
  { title: "Goosebumps",                     artist: "Travis Scott",                   bpm: 130, duration: 243, genres: ["hiphop"] },
  { title: "Run This Town",                  artist: "Jay-Z ft. Rihanna & Kanye West", bpm: 137, duration: 267, genres: ["hiphop"] },
  { title: "Paris",                          artist: "Jay-Z & Kanye West",             bpm: 127, duration: 218, genres: ["hiphop"] },
  { title: "Jumpman",                        artist: "Drake & Future",                 bpm:  91, duration: 242, genres: ["hiphop"] },
  { title: "In My Feelings",                 artist: "Drake",                          bpm:  91, duration: 217, genres: ["hiphop"] },
  { title: "Life is Good",                   artist: "Future ft. Drake",               bpm: 130, duration: 242, genres: ["hiphop"] },
  { title: "Bad and Boujee",                 artist: "Migos",                          bpm: 130, duration: 343, genres: ["hiphop"] },
  { title: "Work",                           artist: "Rihanna ft. Drake",              bpm:  96, duration: 219, genres: ["hiphop"] },

  // ─── ÉLECTRO ─────────────────────────────────────────────────────────────── ~93 min
  { title: "Harder, Better, Faster, Stronger", artist: "Daft Punk",                   bpm: 123, duration: 226, genres: ["electro"] },
  { title: "One More Time",                  artist: "Daft Punk",                     bpm: 123, duration: 320, genres: ["electro"] },
  { title: "Get Lucky",                      artist: "Daft Punk ft. Pharrell Williams",bpm: 116, duration: 247, genres: ["electro"] },
  { title: "Levels",                         artist: "Avicii",                        bpm: 126, duration: 339, genres: ["electro"] },
  { title: "Wake Me Up",                     artist: "Avicii",                        bpm: 124, duration: 272, genres: ["electro"] },
  { title: "Titanium",                       artist: "David Guetta ft. Sia",          bpm: 126, duration: 245, genres: ["electro"] },
  { title: "Turn Me On",                     artist: "David Guetta ft. Nicki Minaj",  bpm: 128, duration: 215, genres: ["electro"] },
  { title: "Animals",                        artist: "Martin Garrix",                 bpm: 128, duration: 304, genres: ["electro"] },
  { title: "Clarity",                        artist: "Zedd ft. Foxes",                bpm: 128, duration: 235, genres: ["electro"] },
  { title: "The Middle",                     artist: "Zedd, Maren Morris & Grey",     bpm: 120, duration: 194, genres: ["electro"] },
  { title: "Pump It",                        artist: "The Black Eyed Peas",           bpm: 154, duration: 213, genres: ["electro"] },
  { title: "I Gotta Feeling",                artist: "The Black Eyed Peas",           bpm: 128, duration: 289, genres: ["electro"] },
  { title: "Yeah!",                          artist: "Usher",                         bpm: 127, duration: 234, genres: ["electro"] },
  { title: "Lean On",                        artist: "Major Lazer & DJ Snake",        bpm:  98, duration: 177, genres: ["electro"] },
  { title: "Summer",                         artist: "Calvin Harris",                 bpm: 128, duration: 222, genres: ["electro"] },
  { title: "We Found Love",                  artist: "Rihanna ft. Calvin Harris",     bpm: 128, duration: 216, genres: ["electro"] },
  { title: "This Is What You Came For",      artist: "Calvin Harris ft. Rihanna",     bpm: 124, duration: 230, genres: ["electro"] },
  { title: "Feel So Close",                  artist: "Calvin Harris",                 bpm: 128, duration: 221, genres: ["electro"] },
  { title: "Don't You Worry Child",          artist: "Swedish House Mafia ft. John Martin", bpm: 128, duration: 209, genres: ["electro"] },
  { title: "Save the World",                 artist: "Swedish House Mafia",           bpm: 128, duration: 274, genres: ["electro"] },
  { title: "Rather Be",                      artist: "Clean Bandit ft. Jess Glynne",  bpm: 120, duration: 245, genres: ["electro"] },
  { title: "Blinding Lights",                artist: "The Weeknd",                    bpm: 171, duration: 200, genres: ["electro"] },
  { title: "Firestone",                      artist: "Kygo ft. Conrad Sewell",        bpm: 104, duration: 248, genres: ["electro"] },

  // ─── ROCK ────────────────────────────────────────────────────────────────── ~94 min
  { title: "Don't Stop Me Now",              artist: "Queen",                         bpm: 156, duration: 210, genres: ["rock"] },
  { title: "Thunderstruck",                  artist: "AC/DC",                         bpm: 134, duration: 292, genres: ["rock"] },
  { title: "Highway to Hell",                artist: "AC/DC",                         bpm: 116, duration: 208, genres: ["rock"] },
  { title: "Back in Black",                  artist: "AC/DC",                         bpm:  92, duration: 255, genres: ["rock"] },
  { title: "Enter Sandman",                  artist: "Metallica",                     bpm: 123, duration: 332, genres: ["rock"] },
  { title: "Welcome to the Jungle",          artist: "Guns N' Roses",                 bpm: 124, duration: 273, genres: ["rock"] },
  { title: "Sweet Child O' Mine",            artist: "Guns N' Roses",                 bpm: 127, duration: 355, genres: ["rock"] },
  { title: "Mr. Brightside",                 artist: "The Killers",                   bpm: 148, duration: 223, genres: ["rock"] },
  { title: "Somebody Told Me",               artist: "The Killers",                   bpm: 130, duration: 188, genres: ["rock"] },
  { title: "Seven Nation Army",              artist: "The White Stripes",             bpm: 124, duration: 232, genres: ["rock"] },
  { title: "Black Betty",                    artist: "Ram Jam",                       bpm: 163, duration: 235, genres: ["rock"] },
  { title: "Living on a Prayer",             artist: "Bon Jovi",                      bpm: 123, duration: 249, genres: ["rock"] },
  { title: "Eye of the Tiger",               artist: "Survivor",                      bpm: 109, duration: 244, genres: ["rock"] },
  { title: "Run to the Hills",               artist: "Iron Maiden",                   bpm: 174, duration: 234, genres: ["rock"] },
  { title: "Smells Like Teen Spirit",        artist: "Nirvana",                       bpm: 116, duration: 301, genres: ["rock"] },
  { title: "Born to Run",                    artist: "Bruce Springsteen",             bpm: 168, duration: 270, genres: ["rock"] },
  { title: "Everlong",                       artist: "Foo Fighters",                  bpm: 158, duration: 251, genres: ["rock"] },
  { title: "Jump",                           artist: "Van Halen",                     bpm: 127, duration: 242, genres: ["rock"] },
  { title: "Pour Some Sugar on Me",          artist: "Def Leppard",                   bpm: 131, duration: 268, genres: ["rock"] },
  { title: "Rock You Like a Hurricane",      artist: "Scorpions",                     bpm: 162, duration: 250, genres: ["rock"] },
  { title: "Paranoid",                       artist: "Black Sabbath",                 bpm: 165, duration: 172, genres: ["rock"] },
  { title: "Welcome to the Black Parade",    artist: "My Chemical Romance",           bpm: 172, duration: 313, genres: ["rock"] },

  // ─── LO-FI / AMBIANT ─────────────────────────────────────────────────────── ~106 min
  { title: "Lady Brown",                     artist: "Nujabes ft. Cise Starr",        bpm:  97, duration: 199, genres: ["lofi"] },
  { title: "Luv(sic) Part 2",               artist: "Nujabes ft. Shing02",           bpm:  83, duration: 273, genres: ["lofi"] },
  { title: "Reflection Eternal",             artist: "Nujabes",                       bpm:  85, duration: 263, genres: ["lofi"] },
  { title: "After Clouds",                   artist: "Nujabes",                       bpm:  86, duration: 260, genres: ["lofi"] },
  { title: "Ordinary Joe",                   artist: "Nujabes",                       bpm:  91, duration: 238, genres: ["lofi"] },
  { title: "Battlecry",                      artist: "Nujabes ft. Shing02",           bpm:  84, duration: 268, genres: ["lofi"] },
  { title: "Feather",                        artist: "Nujabes ft. Cise Starr & AKIN", bpm:  85, duration: 286, genres: ["lofi"] },
  { title: "Shiki no Uta",                   artist: "Nujabes ft. MINMI",             bpm:  86, duration: 259, genres: ["lofi"] },
  { title: "Kong",                           artist: "Bonobo",                        bpm:  94, duration: 238, genres: ["lofi"] },
  { title: "Kiara",                          artist: "Bonobo",                        bpm:  97, duration: 230, genres: ["lofi"] },
  { title: "Kerala",                         artist: "Bonobo",                        bpm:  78, duration: 325, genres: ["lofi"] },
  { title: "Cirrus",                         artist: "Bonobo",                        bpm:  90, duration: 326, genres: ["lofi"] },
  { title: "Prelude",                        artist: "Bonobo",                        bpm:  85, duration: 236, genres: ["lofi"] },
  { title: "Gypsy",                          artist: "Bonobo",                        bpm:  95, duration: 357, genres: ["lofi"] },
  { title: "Ketto",                          artist: "Bonobo",                        bpm:  95, duration: 326, genres: ["lofi"] },
  { title: "Recurring",                      artist: "Bonobo",                        bpm:  90, duration: 293, genres: ["lofi"] },
  { title: "Awake",                          artist: "Tycho",                         bpm:  90, duration: 329, genres: ["lofi"] },
  { title: "Montana",                        artist: "Tycho",                         bpm:  96, duration: 269, genres: ["lofi"] },
  { title: "Dive",                           artist: "Tycho",                         bpm:  90, duration: 316, genres: ["lofi"] },
  { title: "See",                            artist: "Tycho",                         bpm:  88, duration: 337, genres: ["lofi"] },
  { title: "Time (You and I)",               artist: "Khruangbin",                    bpm:  90, duration: 248, genres: ["lofi"] },
  { title: "Lady and Man",                   artist: "Khruangbin",                    bpm:  88, duration: 257, genres: ["lofi"] },
  { title: "Pelota",                         artist: "Khruangbin",                    bpm:  92, duration: 253, genres: ["lofi"] },

  // ─── 🔥 SPÉCIAL MYRIAM (175+ BPM) ──────────────────────────────────────── ~90 min
  { title: "Battery",                        artist: "Metallica",                     bpm: 192, duration: 312, genres: ["myriam"] },
  { title: "Blackened",                      artist: "Metallica",                     bpm: 190, duration: 399, genres: ["myriam"] },
  { title: "Master of Puppets",              artist: "Metallica",                     bpm: 212, duration: 515, genres: ["myriam"] },
  { title: "Ride the Lightning",             artist: "Metallica",                     bpm: 182, duration: 397, genres: ["myriam"] },
  { title: "Raining Blood",                  artist: "Slayer",                        bpm: 229, duration: 249, genres: ["myriam"] },
  { title: "Angel of Death",                 artist: "Slayer",                        bpm: 212, duration: 283, genres: ["myriam"] },
  { title: "Reign in Blood",                 artist: "Slayer",                        bpm: 216, duration: 156, genres: ["myriam"] },
  { title: "Postmortem",                     artist: "Slayer",                        bpm: 196, duration: 264, genres: ["myriam"] },
  { title: "B.Y.O.B.",                       artist: "System of a Down",              bpm: 200, duration: 213, genres: ["myriam"] },
  { title: "Chop Suey!",                     artist: "System of a Down",              bpm: 186, duration: 220, genres: ["myriam"] },
  { title: "Holiday",                        artist: "Green Day",                     bpm: 193, duration: 231, genres: ["myriam"] },
  { title: "American Idiot",                 artist: "Green Day",                     bpm: 189, duration: 174, genres: ["myriam"] },
  { title: "Basket Case",                    artist: "Green Day",                     bpm: 175, duration: 175, genres: ["myriam"] },
  { title: "Ace of Spades",                  artist: "Motörhead",                     bpm: 183, duration: 168, genres: ["myriam"] },
  { title: "Overkill",                       artist: "Motörhead",                     bpm: 182, duration: 305, genres: ["myriam"] },
  { title: "Iron Fist",                      artist: "Motörhead",                     bpm: 175, duration: 175, genres: ["myriam"] },
  { title: "Blitzkrieg Bop",                 artist: "Ramones",                       bpm: 175, duration: 130, genres: ["myriam"] },
  { title: "I Wanna Be Sedated",             artist: "Ramones",                       bpm: 176, duration: 132, genres: ["myriam"] },
  { title: "Rockaway Beach",                 artist: "Ramones",                       bpm: 177, duration: 124, genres: ["myriam"] },
  { title: "Sheena Is a Punk Rocker",        artist: "Ramones",                       bpm: 175, duration: 165, genres: ["myriam"] },
  { title: "Teenage Lobotomy",               artist: "Ramones",                       bpm: 185, duration: 121, genres: ["myriam"] },
  { title: "Highway Star",                   artist: "Deep Purple",                   bpm: 187, duration: 369, genres: ["myriam"] },
  { title: "Surfin' Bird",                   artist: "The Trashmen",                  bpm: 181, duration: 156, genres: ["myriam"] },
];
