// Bibliothèque curatée : titres connus, BPMs vérifiés, durées en secondes.
// genres: motown | hiphop | electro | rock | lofi | myriam (Easter egg 180+ BPM)

const MUSIC_LIBRARY = [

  // ─── MOTOWN / SOUL ────────────────────────────────────────────────────────
  { title: "Dancing in the Street",          artist: "Martha Reeves & The Vandellas",  bpm: 126, duration: 161, genres: ["motown"] },
  { title: "Heat Wave",                      artist: "Martha Reeves & The Vandellas",  bpm: 167, duration: 164, genres: ["motown"] },
  { title: "Nowhere to Run",                 artist: "Martha Reeves & The Vandellas",  bpm: 130, duration: 174, genres: ["motown"] },
  { title: "I Can't Help Myself",            artist: "Four Tops",                      bpm: 127, duration: 165, genres: ["motown"] },
  { title: "Reach Out I'll Be There",        artist: "Four Tops",                      bpm: 120, duration: 174, genres: ["motown"] },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye",                 bpm: 117, duration: 194, genres: ["motown"] },
  { title: "Ain't No Mountain High Enough",  artist: "Marvin Gaye & Tammi Terrell",   bpm: 129, duration: 147, genres: ["motown"] },
  { title: "What's Going On",                artist: "Marvin Gaye",                   bpm: 101, duration: 234, genres: ["motown"] },
  { title: "Superstition",                   artist: "Stevie Wonder",                 bpm: 101, duration: 245, genres: ["motown"] },
  { title: "Signed, Sealed, Delivered",      artist: "Stevie Wonder",                 bpm: 109, duration: 161, genres: ["motown"] },
  { title: "Uptight (Everything's Alright)", artist: "Stevie Wonder",                 bpm: 134, duration: 174, genres: ["motown"] },
  { title: "Sir Duke",                       artist: "Stevie Wonder",                 bpm: 107, duration: 232, genres: ["motown"] },
  { title: "Master Blaster (Jammin')",       artist: "Stevie Wonder",                 bpm: 131, duration: 308, genres: ["motown"] },
  { title: "Higher Ground",                  artist: "Stevie Wonder",                 bpm: 126, duration: 226, genres: ["motown"] },
  { title: "Ain't Too Proud to Beg",         artist: "The Temptations",               bpm: 120, duration: 153, genres: ["motown"] },
  { title: "My Girl",                        artist: "The Temptations",               bpm: 105, duration: 165, genres: ["motown"] },
  { title: "Get Ready",                      artist: "The Temptations",               bpm: 135, duration: 159, genres: ["motown"] },
  { title: "Ball of Confusion",              artist: "The Temptations",               bpm:  80, duration: 249, genres: ["motown"] },
  { title: "Papa Was a Rollin' Stone",       artist: "The Temptations",               bpm:  90, duration: 414, genres: ["motown"] },
  { title: "I Want You Back",                artist: "Jackson 5",                     bpm:  98, duration: 179, genres: ["motown"] },
  { title: "ABC",                            artist: "Jackson 5",                     bpm:  94, duration: 177, genres: ["motown"] },
  { title: "Stop! In the Name of Love",      artist: "The Supremes",                  bpm: 115, duration: 173, genres: ["motown"] },
  { title: "Baby Love",                      artist: "The Supremes",                  bpm: 136, duration: 158, genres: ["motown"] },
  { title: "You Keep Me Hangin' On",         artist: "The Supremes",                  bpm: 128, duration: 163, genres: ["motown"] },
  { title: "Going to a Go-Go",               artist: "The Miracles",                  bpm: 129, duration: 158, genres: ["motown"] },
  { title: "Shop Around",                    artist: "The Miracles",                  bpm: 120, duration: 167, genres: ["motown"] },
  { title: "Tears of a Clown",               artist: "Smokey Robinson & The Miracles",bpm: 128, duration: 179, genres: ["motown"] },
  { title: "Do You Love Me",                 artist: "The Contours",                  bpm: 151, duration: 173, genres: ["motown"] },
  { title: "Shotgun",                        artist: "Jr. Walker & The All Stars",    bpm: 120, duration: 185, genres: ["motown"] },

  // ─── HIP-HOP ──────────────────────────────────────────────────────────────
  { title: "Lose Yourself",                  artist: "Eminem",                        bpm: 171, duration: 326, genres: ["hiphop"] },
  { title: "Stronger",                       artist: "Kanye West",                    bpm: 104, duration: 312, genres: ["hiphop"] },
  { title: "POWER",                          artist: "Kanye West",                    bpm: 154, duration: 292, genres: ["hiphop"] },
  { title: "All Falls Down",                 artist: "Kanye West",                    bpm:  82, duration: 237, genres: ["hiphop"] },
  { title: "HUMBLE.",                        artist: "Kendrick Lamar",                bpm: 150, duration: 177, genres: ["hiphop"] },
  { title: "m.A.A.d city",                   artist: "Kendrick Lamar",                bpm: 109, duration: 353, genres: ["hiphop"] },
  { title: "Swimming Pools",                 artist: "Kendrick Lamar",                bpm:  84, duration: 314, genres: ["hiphop"] },
  { title: "Mask Off",                       artist: "Future",                        bpm: 150, duration: 204, genres: ["hiphop"] },
  { title: "SICKO MODE",                     artist: "Travis Scott",                  bpm: 155, duration: 313, genres: ["hiphop"] },
  { title: "Run This Town",                  artist: "Jay-Z ft. Rihanna & Kanye West",bpm: 137, duration: 267, genres: ["hiphop"] },
  { title: "Jumpman",                        artist: "Drake & Future",                bpm:  91, duration: 242, genres: ["hiphop"] },
  { title: "Bad and Boujee",                 artist: "Migos",                         bpm: 130, duration: 343, genres: ["hiphop"] },

  // ─── ÉLECTRO ──────────────────────────────────────────────────────────────
  { title: "Harder, Better, Faster, Stronger", artist: "Daft Punk",                  bpm: 123, duration: 226, genres: ["electro"] },
  { title: "One More Time",                  artist: "Daft Punk",                    bpm: 123, duration: 320, genres: ["electro"] },
  { title: "Get Lucky",                      artist: "Daft Punk ft. Pharrell Williams",bpm: 116, duration: 247, genres: ["electro"] },
  { title: "Levels",                         artist: "Avicii",                       bpm: 126, duration: 339, genres: ["electro"] },
  { title: "Wake Me Up",                     artist: "Avicii",                       bpm: 124, duration: 272, genres: ["electro"] },
  { title: "Titanium",                       artist: "David Guetta ft. Sia",         bpm: 126, duration: 245, genres: ["electro"] },
  { title: "Turn Me On",                     artist: "David Guetta ft. Nicki Minaj", bpm: 128, duration: 215, genres: ["electro"] },
  { title: "Animals",                        artist: "Martin Garrix",                bpm: 128, duration: 304, genres: ["electro"] },
  { title: "Clarity",                        artist: "Zedd ft. Foxes",               bpm: 128, duration: 235, genres: ["electro"] },
  { title: "Pump It",                        artist: "The Black Eyed Peas",          bpm: 154, duration: 213, genres: ["electro"] },
  { title: "I Gotta Feeling",                artist: "The Black Eyed Peas",          bpm: 128, duration: 289, genres: ["electro"] },
  { title: "Yeah!",                          artist: "Usher",                        bpm: 127, duration: 234, genres: ["electro"] },
  { title: "Lean On",                        artist: "Major Lazer & DJ Snake",       bpm:  98, duration: 177, genres: ["electro"] },

  // ─── ROCK ─────────────────────────────────────────────────────────────────
  { title: "Don't Stop Me Now",              artist: "Queen",                        bpm: 156, duration: 210, genres: ["rock"] },
  { title: "Thunderstruck",                  artist: "AC/DC",                        bpm: 134, duration: 292, genres: ["rock"] },
  { title: "Highway to Hell",               artist: "AC/DC",                        bpm: 116, duration: 208, genres: ["rock"] },
  { title: "Back in Black",                  artist: "AC/DC",                        bpm:  92, duration: 255, genres: ["rock"] },
  { title: "Enter Sandman",                  artist: "Metallica",                    bpm: 123, duration: 332, genres: ["rock"] },
  { title: "Welcome to the Jungle",          artist: "Guns N' Roses",                bpm: 124, duration: 273, genres: ["rock"] },
  { title: "Sweet Child O' Mine",            artist: "Guns N' Roses",                bpm: 127, duration: 355, genres: ["rock"] },
  { title: "Mr. Brightside",                 artist: "The Killers",                  bpm: 148, duration: 223, genres: ["rock"] },
  { title: "Somebody Told Me",               artist: "The Killers",                  bpm: 130, duration: 188, genres: ["rock"] },
  { title: "Seven Nation Army",              artist: "The White Stripes",            bpm: 124, duration: 232, genres: ["rock"] },
  { title: "Black Betty",                    artist: "Ram Jam",                      bpm: 163, duration: 235, genres: ["rock"] },
  { title: "Living on a Prayer",             artist: "Bon Jovi",                     bpm: 123, duration: 249, genres: ["rock"] },
  { title: "Eye of the Tiger",               artist: "Survivor",                     bpm: 109, duration: 244, genres: ["rock"] },
  { title: "Run to the Hills",               artist: "Iron Maiden",                  bpm: 174, duration: 234, genres: ["rock"] },
  { title: "Smells Like Teen Spirit",        artist: "Nirvana",                      bpm: 116, duration: 301, genres: ["rock"] },
  { title: "Born to Run",                    artist: "Bruce Springsteen",            bpm: 168, duration: 270, genres: ["rock"] },
  { title: "Everlong",                       artist: "Foo Fighters",                 bpm: 158, duration: 251, genres: ["rock"] },

  // ─── LO-FI / AMBIANT ──────────────────────────────────────────────────────
  { title: "Lady Brown",                     artist: "Nujabes ft. Cise Starr",       bpm:  97, duration: 199, genres: ["lofi"] },
  { title: "Luv(sic) Part 2",               artist: "Nujabes ft. Shing02",          bpm:  83, duration: 273, genres: ["lofi"] },
  { title: "Reflection Eternal",             artist: "Nujabes",                      bpm:  85, duration: 263, genres: ["lofi"] },
  { title: "After Clouds",                   artist: "Nujabes",                      bpm:  86, duration: 260, genres: ["lofi"] },
  { title: "Ordinary Joe",                   artist: "Nujabes",                      bpm:  91, duration: 238, genres: ["lofi"] },
  { title: "Kong",                           artist: "Bonobo",                       bpm:  94, duration: 238, genres: ["lofi"] },
  { title: "Kiara",                          artist: "Bonobo",                       bpm:  97, duration: 230, genres: ["lofi"] },
  { title: "Kerala",                         artist: "Bonobo",                       bpm:  78, duration: 325, genres: ["lofi"] },
  { title: "Cirrus",                         artist: "Bonobo",                       bpm:  90, duration: 326, genres: ["lofi"] },

  // ─── 🔥 SPÉCIAL MYRIAM (180+ BPM) ─────────────────────────────────────────
  { title: "Battery",                        artist: "Metallica",                    bpm: 192, duration: 312, genres: ["myriam"] },
  { title: "Blackened",                      artist: "Metallica",                    bpm: 190, duration: 399, genres: ["myriam"] },
  { title: "Holiday",                        artist: "Green Day",                    bpm: 193, duration: 231, genres: ["myriam"] },
  { title: "American Idiot",                 artist: "Green Day",                    bpm: 189, duration: 174, genres: ["myriam"] },
  { title: "Basket Case",                    artist: "Green Day",                    bpm: 175, duration: 175, genres: ["myriam"] },
  { title: "Ace of Spades",                  artist: "Motörhead",                    bpm: 183, duration: 168, genres: ["myriam"] },
  { title: "Blitzkrieg Bop",                 artist: "Ramones",                      bpm: 175, duration: 130, genres: ["myriam"] },
  { title: "I Wanna Be Sedated",             artist: "Ramones",                      bpm: 176, duration: 132, genres: ["myriam"] },
  { title: "Highway Star",                   artist: "Deep Purple",                  bpm: 187, duration: 369, genres: ["myriam"] },
  { title: "Surfin' Bird",                   artist: "The Trashmen",                 bpm: 181, duration: 156, genres: ["myriam"] },
];
